#%RAML 0.8
title: Products Pipeline
version: v1
mediaType: application/json
baseUri: http://pipeline.tesco.com/{version}
traits:
  - requestHeaders: !include ../../shared/v1.0/traits/requestHeaders.yaml
schemas:
  - productsSchema: !include schemas/productList.json
  - errorSchema: !include ../../shared/v1.0/schemas/pipelineError.json 
/{region}/products/:
  get:
   is: [requestHeaders]
   description: |
             The purpose of this pipeline is to fetch product info based on one or more identifiers of a single type. Identifiers are TPNBs and TPNCs. The maximum number of identifiers which can be queried in a single request is 20. One of the supported Identifier type is mandatory to be sent into the pipeline - Either of TPNB or TPNC is mandatory.
             
             Only one identifier type should be sent in a single request - All IDs are either TPNCs or TPNBs.
    
             Examples:
             
             1. Fetch Product, price and offer details based on a TPNC:  
               http://pipeline.tesco.com/v1/gb/products?tpnc=67798197

             2. Fetch Product, price and offer details based on multiple TPNBs and sort by price - high to low:  
               http://pipeline.tesco.com/v1/gb/products?tpnb=67798197&tpnb=67798198&orderByKey=price&orderBy=desc
                                                 
       
   queryParameters:
     tpnb:
      description: Tesco Product Number - Base Product (UK Identifier) e.g. 050000304
      type: string
      repeat: true
     tpnc:
      description: Tesco Product Number - Consumer Unit (UK Identifier) e.g. 257480716.
      type: string
      repeat: true
     orderByKey:
      description: Sort by Field - Sort on "price" or "title"
      type: string
      "enum": [ "price", "title" ]
      required: false
     orderBy:
      description: Sort order. "asc" is to sort low to high. "desc" is to sort high to low. If omitted, pipeline will use "asc" as the default value.
      type: string
      "enum": [ "asc", "desc" ]
      default: "asc"
      required: false
   responses:
      200:
        body:          
          application/json:
            schema:  productsSchema
            example: !include examples/products.json
      206:
        description: |
          The pipeline has returned a partial response. Either some of the items in the list has been filtered out due to non-availability of mandatory fields defined in the pipeline contract or retrieving optional fields failed. The "Warning" HTTP header will be set in the response which will contain a comma separated list of Product IDs (TPNBs or TPNCs) that have been filtered out in the response. For Ex : Warning: 199 - "67891345,67891333"
        body:          
          application/json:
            schema:  productsSchema
            example: !include examples/products.json
      400:
        body:
          application/json:
            schema:  errorSchema
            example: !include examples/error4xx.json
      500:
        body:
          application/json:
            schema:  errorSchema
            example: !include examples/error5xx.json

