#%RAML 0.8
title: Digital Content Pipeline
version: v1.0
baseUri: http://pipeline.tesco.com/{version}

traits:  
  - requestHeaders: !include ../../shared/v1.0/traits/requestHeaders.yaml
  - paginated: !include ../../shared/v1.0/traits/paginated.yaml
schemas:
  - digitalcontentsSchema: !include ./schemas/digitalcontent.json
  - pipelineErrorSchema: !include ../../shared/v1.0/schemas/pipelineError.json
/{region}/digitalcontent:
  get:
    is: [requestHeaders, paginated ]
    description: |
           Digital Content Pipeline will call into the Digital Content API to fetch the marketing content and assets that will be rendered on the UI.
           The query params - metadata and queryFilter - are mutually exclusive. One and only one of these two query params is mandatory.
           
           Examples:
           1. Based on queryFilter:
             http://pipeline.tesco.com/v1/gb/digitalcontent?queryFilter=TeamSite/Templating/DCR/Type:header/logo
     
           2. Query based on metadata:
           http://pipeline.tesco.com/v1/gb/digitalcontent?metadata=title+summary
           
    queryParameters:
         customerSegment:
           displayName: customerSegment
           type: string
           description: Depending upon the customer segment the digital content will vary.
           example: Regular
           required: false
         metadata:
           displayName: metadata
           type: string
           description: Metadata filters, separated by +, to be applied when searching for the digital content/assets.
           example: title+summary+thumbnail
           required: false
         queryFilter:
           displayName: queryFilter
           type: string
           description: Query filters to be applied when searching for the digital content/assets.
           example: q=category:product
           required: false
         deviceFamily:
           displayName: deviceFamily
           type: string
           description: Device family
           example: PC, Mobile, Tablet, etc.
           required: false
         relatedAssetsBy:
           displayName: relatedAssetsBy
           type: string
           description: This will be one of the metadata field list. Multiple fields can be specified with + delimiter 
           example: AbsoluteVpath+AreaRelativePath
           required: true
         catalogName:
           displayName: catalogName
           type: string
           description: Name of the catalog from where to fetch digital content
           example: horizon
           required: true
    responses:   
      200:
        body:
          application/json:
            schema: digitalcontentsSchema
            example: !include ./examples/digitalcontent.json
      206:
        body:
          application/json:
            schema: digitalcontentsSchema
            example: !include ./examples/digitalcontentPartial.json
      400:
        body:
          application/json:
            schema: pipelineErrorSchema
            example: !include ./examples/pipelineError400.json
      404:
        body:
          application/json:
            schema:  pipelineErrorSchema
            example: !include ./examples/pipelineError404.json
      500:
        body:
          application/json:
            schema:  pipelineErrorSchema
            example: !include ./examples/pipelineError500.json 
