#%RAML 0.8
title: Digital Content Pipeline
version: v1.0
baseUri: http://pipeline.tesco.com/{version}/{region}/
documentation:
 - title: Home
   content: |
     Digital Content Pipeline will call into the Digital Content API to fetch the marketing content and assets that will be rendered on the UI.
     Examples:
     
     1. Based on Asset ID:
     http://pipeline.tesco.com/v1/gb/digitalcontent?id=ASSET_ID_00011+ASSET_ID_11234+ASSET_ID_998034
     
     2. Query based on Asset metadata:
     http://pipeline.tesco.com/v1/gb/digitalcontent?metadata=title+summary&queryFilter=category:products
traits:  
  - requestHeaders: !include ../../shared/v1.0/traits/requestHeaders.yaml
  - paginated: !include ../../shared/v1.0/traits/paginated.yaml
schemas:
  - digitalcontentsSchema: !include ./schemas/digitalcontent.json
  - pipelineErrorSchema: !include ../../shared/v1.0/schemas/pipelineError.json
/digitalcontent:
  get:
    is: [requestHeaders, paginated ]
    description: Get the digital contents.
    queryParameters:
         id:
           displayName: id
           type: string
           description: Asset Ids separated by + delimiter
           example: ASST_ID_00011+ASST_ID_11234+ASST_ID_998034
           required: true
         customerSegment:
           displayName: customerSegment
           type: string
           description: Depending upon the customer segment the digital content will vary.
           example: Regular
           required: false
         metadata:
           displayName: metadata
           type: string
           description: Metadata filters, separated by +, to be applied when searching for the digital content/assets.
           example: title+summary+thumbnail
           required: false
         queryFilter:
           displayName: queryFilter
           type: string
           description: Query filters to be applied when searching for the digital content/assets.
           example: q=category:product
           required: false
         deviceFamily:
           displayName: deviceFamily
           type: string
           description: Device family
           example: PC, Mobile, Tablet, etc.
           required: false
    responses:   
      200:
        body:
          application/json:
            schema: digitalcontentsSchema
            example: !include ./examples/digitalcontent.json
      400:
        body:
          application/json:
            schema: pipelineErrorSchema
            example: !include ./examples/pipelineError400.json
      404:
        body:
          application/json:
            schema:  pipelineErrorSchema
            example: !include ./examples/pipelineError404.json
      500:
        body:
          application/json:
            schema:  pipelineErrorSchema
            example: !include ./examples/pipelineError500.json 
