#%RAML 0.8
title: Device Pipeline
version: v1
baseUri: http://pipeline.tesco.com/{version}
traits:  
  - requestHeaders: !include ../../shared/v1.0/traits/requestHeaders.yaml
schemas:
  - deviceSchema: !include ./schemas/device.json
  - pipelineErrorSchema: !include ../../shared/v1.0/schemas/pipelineError.json
/{region}/device:
  get:
    is: [requestHeaders ]
    description: |
     Device Pipeline will help in identifying the device from where the request is originating from. It uses the user-agent header to determine the device. There are no query parameters that need to be passed in. 
     Example:
     
     http://pipeline.tesco.com/v1/gb/device    
    
    responses:   
      200:
        body:
          application/json:
            schema: deviceSchema
            example: !include ./examples/device.json
      400:
        body:
          application/json:
            schema:  pipelineErrorSchema
            example: !include ./examples/pipelineError400.json
      500:
        body:
          application/json:
            schema:  error5xxSchema
            example: !include ./examples/pipelineError500.json 
