#%RAML 0.8
title: Product
version: v1
baseUri: http://localhost:106/api/{version}
traits:  
  - requestHeaders: !include ../../traits/requestHeaders.yaml
  - multiTenanted: !include ../../traits/multiTenanted.yaml
/product/{id}:
  get: 
   is: [requestHeaders,multiTenanted]
   description: |
      Gets the product detail of a product against id. 
   responses:
      200:
        body:
          application/json:
            #TODO schema: !include productSummary-schema-v1.0.json
            # TODO example: !include productSummary-example-v1.0.json
/product/{barcode}:
  get: 
   is: [requestHeaders,multiTenanted]
   description: |
      Gets the product detail of a product against barcode. 
   responses:
      200:
        body:
          application/json:
            #TODO schema: !include productSummary-schema-v1.0.json
            # TODO example: !include productSummary-example-v1.0.json